#ifndef IDENTIFICADORES_H
#define IDENTIFICADORES_H

//MENU PRINCIPAL

//MENU SEC: NODOS
#define ID_AGREGAR 101
#define ID_ELIMINAR 102
#define ID_SALIR 103

//MODAL AGG NODO
#define STT_NUMERO 201
#define EDT_NUMERO 202
#define STT_NOMBRE 203
#define EDT_NOMBRE 204
#define ID_BTN_AGREGAR_NODO 205

//LISTAR NODOS
#define ID_PREORDEN 301
#define ID_POSTORDEN 302
#define ID_INORDEN 303

HWND hwndPrincipal;
BOOL CALLBACK DlgAgregarNodoProc(HWND hwnd,UINT message,WPARAM wParam,LPARAM lParam);
#endif //IDENTIFICADORES_H
